services:
  - type: web
    name: huddle-server
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 3001
      - key: CLIENT_URL
        sync: false
